# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab6e25fa613f64ca6c8f1191a7d76f9d8d8643692cbe883b9430258c0c45ba57622b62446020d06f8fe17de1fa12c4fb485ceb1db7b49caf678d67f981181b81

test:
  secret_key_base: 8f1692f8530a939bb976e529cc035ed898c41b39e7a230ae9df03945503c6438f4b9ca9c7eb6406e868a57fc8838d10a0697bfb6116d8e9c1bb55e0f49b05289

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
